"""
Streamlit Dashboard for Social Media Marketing Agent
=====================================================
Web interface for viewing and editing post drafts generated by Gemini.
Allows manual editing of Georgian text before publishing.
"""

import streamlit as st
import os
from database import Database
from text_generator import TextGenerator
from PIL import Image


# Page configuration
st.set_page_config(
    page_title="🍯 სოციალური მედიის მარკეტინგის დაშბორდი",
    page_icon="🍯",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS for Georgian text
st.markdown("""
<style>
    .main-header {
        font-size: 2.5rem;
        font-weight: bold;
        color: #FF9800;
        text-align: center;
        margin-bottom: 2rem;
    }
    .draft-card {
        background-color: #f5f5f5;
        padding: 1.5rem;
        border-radius: 10px;
        margin-bottom: 1rem;
    }
    .stTextArea textarea {
        font-size: 1.1rem;
        line-height: 1.6;
    }
</style>
""", unsafe_allow_html=True)


def initialize_session_state():
    """Initialize Streamlit session state."""
    if 'db' not in st.session_state:
        st.session_state.db = Database()

    if 'text_gen' not in st.session_state:
        api_key = os.getenv("GOOGLE_GEMINI_API_KEY")
        if api_key:
            st.session_state.text_gen = TextGenerator(api_key)
        else:
            st.session_state.text_gen = None


def main():
    """Main dashboard application."""
    initialize_session_state()

    db = st.session_state.db

    # Header
    st.markdown('<div class="main-header">🍯 სოციალური მედიის მარკეტინგის დაშბორდი</div>', unsafe_allow_html=True)

    # Sidebar
    with st.sidebar:
        st.header("📋 ნავიგაცია")

        page = st.radio(
            "აირჩიე გვერდი:",
            ["📝 დრაფტების მართვა", "➕ ახალი პოსტის შექმნა", "📊 სტატისტიკა"],
            label_visibility="collapsed"
        )

        st.divider()

        # Quick stats
        st.subheader("📊 სწრაფი სტატისტიკა")
        all_drafts = db.get_all_drafts()
        draft_count = len([d for d in all_drafts if d['status'] == 'draft'])
        approved_count = len([d for d in all_drafts if d['status'] == 'approved'])

        st.metric("დრაფტები", draft_count)
        st.metric("დამტკიცებული", approved_count)

    # Main content area
    if page == "📝 დრაფტების მართვა":
        show_drafts_page(db)

    elif page == "➕ ახალი პოსტის შექმნა":
        show_create_page(db)

    elif page == "📊 სტატისტიკა":
        show_statistics_page(db)


def show_drafts_page(db: Database):
    """Show and edit drafts."""
    st.header("📝 დრაფტების მართვა")

    # Get draft ID from URL parameters (if sent from Telegram)
    query_params = st.query_params
    selected_draft_id = query_params.get("draft_id", None)

    if selected_draft_id:
        selected_draft_id = int(selected_draft_id)

    # Filter options
    col1, col2 = st.columns([3, 1])

    with col1:
        status_filter = st.selectbox(
            "ფილტრი სტატუსით:",
            ["ყველა", "draft", "approved", "published", "rejected"]
        )

    with col2:
        sort_order = st.selectbox("დალაგება:", ["ახალი პირველი", "ძველი პირველი"])

    # Get drafts
    if status_filter == "ყველა":
        drafts = db.get_all_drafts()
    else:
        drafts = db.get_all_drafts(status=status_filter)

    if sort_order == "ძველი პირველი":
        drafts = list(reversed(drafts))

    if not drafts:
        st.info("📭 დრაფტები არ არის.")
        return

    # Display drafts
    for draft in drafts:
        # Highlight if this is the selected draft
        is_selected = (selected_draft_id == draft['id'])

        with st.expander(
            f"{'🔹' if is_selected else '📄'} #{draft['id']} - {draft['honey_type']} ({draft['status']})",
            expanded=is_selected
        ):
            col1, col2 = st.columns([2, 1])

            with col1:
                # Editable text area
                new_text = st.text_area(
                    "ტექსტი:",
                    value=draft['post_text'],
                    height=200,
                    key=f"text_{draft['id']}"
                )

                # Save button
                if st.button(f"💾 ტექსტის შენახვა", key=f"save_{draft['id']}"):
                    if new_text != draft['post_text']:
                        db.update_draft_text(draft['id'], new_text, edited_by="user")
                        st.success("✓ ტექსტი შენახულია!")
                        st.rerun()

                # Status update
                col_a, col_b, col_c = st.columns(3)

                with col_a:
                    if st.button("✅ დამტკიცება", key=f"approve_{draft['id']}"):
                        db.update_draft_status(draft['id'], "approved")
                        st.success("დამტკიცებულია!")
                        st.rerun()

                with col_b:
                    if st.button("❌ უარყოფა", key=f"reject_{draft['id']}"):
                        db.update_draft_status(draft['id'], "rejected")
                        st.warning("უარყოფილია!")
                        st.rerun()

                with col_c:
                    if st.button("🗑️ წაშლა", key=f"delete_{draft['id']}"):
                        db.delete_draft(draft['id'])
                        st.success("წაშლილია!")
                        st.rerun()

            with col2:
                # Display image if available
                if draft['image_path'] and os.path.exists(draft['image_path']):
                    try:
                        image = Image.open(draft['image_path'])
                        st.image(image, caption=f"#{draft['id']}", use_container_width=True)
                    except Exception as e:
                        st.error(f"სურათის ჩატვირთვა ვერ მოხერხდა: {e}")
                else:
                    st.info("📷 სურათი არ არის")

                # Metadata
                st.caption(f"**შექმნილია:** {draft['created_at'][:16]}")
                st.caption(f"**განახლებულია:** {draft['updated_at'][:16]}")

            # Show edit history
            if st.checkbox(f"📜 რედაქტირების ისტორია", key=f"history_{draft['id']}"):
                history = db.get_edit_history(draft['id'])

                if history:
                    for edit in history:
                        st.caption(
                            f"✏️ {edit['edited_at'][:16]} - {edit['edited_by']}"
                        )
                else:
                    st.caption("ისტორია ცარიელია")


def show_create_page(db: Database):
    """Page for creating new posts manually."""
    st.header("➕ ახალი პოსტის შექმნა")

    st.info("💡 ახალი პოსტის შესაქმნელად გამოიყენე Telegram Bot: /create [ძმრის ტიპი]")

    st.divider()

    st.subheader("ხელით შექმნა (მოსაწვდად)")

    honey_type = st.text_input("ძმრის ტიპი:", placeholder="მაგ: ბროწეულის ძმარი")

    post_text = st.text_area(
        "პოსტის ტექსტი:",
        height=200,
        placeholder="დაწერე პოსტი აქ..."
    )

    if st.button("💾 დრაფტის შენახვა"):
        if honey_type and post_text:
            draft_id = db.create_draft(
                honey_type=honey_type,
                post_text=post_text,
                image_path=None
            )
            st.success(f"✓ დრაფტი #{draft_id} შექმნილია!")
        else:
            st.error("❌ გთხოვ, შეავსე ყველა ველი.")


def show_statistics_page(db: Database):
    """Show statistics and analytics."""
    st.header("📊 სტატისტიკა")

    all_drafts = db.get_all_drafts()

    if not all_drafts:
        st.info("📭 მონაცემები არ არის.")
        return

    # Status distribution
    col1, col2, col3, col4 = st.columns(4)

    with col1:
        draft_count = len([d for d in all_drafts if d['status'] == 'draft'])
        st.metric("📝 დრაფტები", draft_count)

    with col2:
        approved_count = len([d for d in all_drafts if d['status'] == 'approved'])
        st.metric("✅ დამტკიცებული", approved_count)

    with col3:
        published_count = len([d for d in all_drafts if d['status'] == 'published'])
        st.metric("🎉 გამოქვეყნებული", published_count)

    with col4:
        rejected_count = len([d for d in all_drafts if d['status'] == 'rejected'])
        st.metric("❌ უარყოფილი", rejected_count)

    st.divider()

    # Recent activity
    st.subheader("🕒 ბოლო აქტივობა")

    recent_drafts = all_drafts[:10]

    for draft in recent_drafts:
        status_emoji = {
            'draft': '📝',
            'approved': '✅',
            'published': '🎉',
            'rejected': '❌'
        }.get(draft['status'], '❓')

        st.caption(
            f"{status_emoji} **#{draft['id']}** - {draft['honey_type']} "
            f"({draft['created_at'][:16]})"
        )

    st.divider()

    # Honey types summary
    st.subheader("🍯 ძმრის ტიპები")

    honey_types = {}
    for draft in all_drafts:
        honey_type = draft['honey_type']
        honey_types[honey_type] = honey_types.get(honey_type, 0) + 1

    for honey_type, count in sorted(honey_types.items(), key=lambda x: x[1], reverse=True):
        st.caption(f"🍯 {honey_type}: **{count}** პოსტი")


# Run the app
if __name__ == "__main__":
    main()
